### PR TITLE
UI tests for tooltips display and task name edition

### PR DESCRIPTION
**Pull request by laurianed**

### CODE REVIEW

**Comment by tobwiens** [comment]
Retest this please

**Comment by tobwiens** [comment]
Retest this please

**Comment by tobwiens** [comment]
@laurianed Can you rebase your PR please, we solved a dependency issue which will make the tests run.

**Comment by laurianed** [comment]
retest this please

**Comment by ShatalovYaroslav** [comment]
LGTM

**Comment by cdiop** [comment]
OKi for me

**Comment by laurianed** [comment]
retest this please

**Pull request merged**
