### PR TITLE
Structure tasks menu

### PR DESCRIPTION
**Pull request by aminelouati**
In this PR we:
1. Structure the Tasks menu by adding three sections: OS, Languages and Containers
2. Delete useless templates 
3. Delete useless template icons

### CODE REVIEW

**Comment by fviale** [comment]
test failed (could be because you removed some workflows)

**Comment by aminelouati** [comment]
re-test this please

**Comment by aminelouati** [comment]
I removed workflows of manuals and controls menus because they are moved to the Catalog. I also removed script_cron.xml and Ldap_query.xml templates moved to other menus and an old template native.xml. Tests failed because of instability.

**Comment by medou-boushab** [comment]
do you  need this extension ".gif"?  There is If.gif and If.png

**Pull request merged**
