### PR TITLE
Add Fork Execution Environment

### PR DESCRIPTION
**Pull request by tobwiens**
Add Fork Execution Environment to the Task model.
Add a listener, which listens to Fork Execution Environment changes.
Add a template inside the Fork Execution Envrionment Docker selection, which will be inserted inside the Fork Environment Script. To give users a starting example.

### CODE REVIEW

**Comment by lpellegr** [comment]
@tobwiens The title looks a bit large :)

**Comment by tobwiens** [comment]
Retest this please.

**Comment by tobwiens** [comment]
@ow2-proactive/developers Two reviews please. 
The jenkins tests are against trydev, if they fail it is not because of this changes.

**Comment by tobwiens** [comment]
@ow2-proactive/developers Two reviews please.
The jenkins tests are against trydev, if they fail it is not because of this changes.

**Comment by marcocast** [comment]
:+1:

**Pull request merged**
