### PR TITLE
STUDIO BUG::In window Get a Workflow from the Catalog: the list of buckets doesn't refresh automatically

### PR DESCRIPTION
**Pull request by chloegugli**

### CODE REVIEW

**Comment by paraita** [comment]
The commits comments are the same, can you put more details in those comments ? or simply squash the comments if the comments are note relevant please

**Comment by paraita** [comment]
Switching this `async` to false isn't going to degrade the studio experience if the network is slow ?

**Comment by chloegugli** [comment]
@paraita Yes, it might be noticeable by the user if the network is really slow

**Comment by marcocast** [comment]
LGTM

**Pull request merged**
