### PR TITLE
add-account-info

### PR DESCRIPTION
**Pull request by oanaBiancaSchiopu**

### CODE REVIEW

**Review by mboussaa — APPROVED** [review]

**Comment by mboussaa** [comment]
@oanaBiancaSchiopu could you please remove the screenshot before merge otherwise it will cause issues thanks

**Comment by fviale** [comment]
@oanaBiancaSchiopu 

can you add more "air" to the popup window margins ?

I think it is done using the css padding properties

**Comment by fviale** [comment]
also, the title "Account Info" should be centered

**Comment by fviale** [comment]
finally, why is username so big ?

**Comment by oanaBiancaSchiopu** [comment]
> finally, why is username so big ?

it's a h3 tag, I can make it smaller if you want

**Review by fviale — APPROVED** [review]

**Pull request merged**
