### PR TITLE
fixes #222 : Language type is lost if Script is cleared 

### LINKED ISSUE #222: Language type is lost if Script is cleared and the workflow is exported
The language type is lost if Script is cleared and the workflow is exported : 

screen shot 2016-02-23 at 11 40 33

Steps to reproduce : 

1. Create a workflow with a python task
2. Click on the python task and delete everything in the Script text area on  the left
3. Export the workflow
4. Import the workflow

### PR DESCRIPTION
**Pull request by sophiesongge**
added jugdement for language to avoid skipping

### CODE REVIEW

**Comment by sophiesongge** [comment]
Retest please

**Comment by tobwiens** [comment]
@sophiesongge I cannot see the changes, the code was re-formatted: It is hard to spot what was changed. Can you explain or point to your changes.

**Comment by sophiesongge** [comment]
I have add "|| model["Language"]"
At the first line :
if (model["Library Path"] && model["Library Path"].length>0 ||
model["Script"] && model["Script"].length>0)
if (model["Library Path"] && model["Library Path"].length>0 ||
model["Script"] && model["Script"].length>0 || model["Language"])
And at the 4th line:
if (model["Script"] && model["Script"].length>0 && !model["Library Path"])
if (model["Script"] && model["Script"].length>0 && !model["Library Path"]
|| model["Language"])

To make sure that the contant will not be skipped if there exist
information about "Language"




2016-05-03 11:50 GMT+02:00 tobwiens <notifications@github.com>:

> @sophiesongge <https://github.com/sophiesongge> I cannot see the changes,
> the code was re-formatted: It is hard to spot what was changed. Can you
> explain or point to your changes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ow2-proactive/studio/pull/251#issuecomment-216482986>
>



-- 

Sophie Song
Tel. @ China: +86 134 26 22 77 71
Tel. @ France: +33 (0)6 20 57 23 06
Homepage:  http://www-sop.inria.fr/members/Ge.Song/index.html
Email: sophiesongge@gmail.com
           ge.song@inria.fr

**Comment by tobwiens** [comment]
Thank you for clarifying. :+1: Looks good for me.

**Comment by sophiesongge** [comment]
Okay, thanks Laurent.

**Pull request merged**
