### PR TITLE
Add unit test for Python formatting script

### PR DESCRIPTION
**Pull request by marcocast**

### CODE REVIEW

**Comment by marcocast** [comment]
2 reviews please?

**Comment by tobwiens** [comment]
:+1: Looks good. Sadly it is bound to the exact script we use.
Looks like we can easily add this for other languages as well.

**Comment by fviale** [comment]
Same remark as tobias, but I don't know how to make it different

**Comment by marcocast** [comment]
@tobwiens  Yes we could add a test for each script type easily, but i felt was out of the scope of this story

**Pull request merged**
