### PR TITLE
Create a new menu for notification services

### PR DESCRIPTION
**Pull request by sophiesongge**
create a new menu for notification services

### CODE REVIEW

**Comment by cdiop** [comment]
LGTM

**Comment by lpellegr** [comment]
Images which have been added should be resized.

@sophiesongge If I understand, Michael and I will have to remove our workflows from the Scheduling projects so that they no longer appear in the _templates_ menu? instead you will include them in the Studio directly?

**Comment by lpellegr** [comment]
I haven't followed the discussions since I was not there but do you know what is the reason to name the new menu _Manuals_?

**Comment by sophiesongge** [comment]
@lpellegr
Thanks.
For the templates, I can find a way to import it from scheduling, but I don't have enough time for this release. So, I think it is better to keep it in Scheduler for now.

**Comment by sophiesongge** [comment]
@lpellegr There is an email talking about this menu, I will send it to you.

**Pull request merged**
