### PR TITLE
Update related to Speed branch from scheduling

### PR DESCRIPTION
**Pull request by lpellegr**

### CODE REVIEW

**Comment by lpellegr** [comment]
@youribonnaffe Could you please have a look?

**Comment by youribonnaffe** [comment]
When adding a environment variable (without setting appendChar value), checking of the workflow will fail (_At [task=Linux] [tag:job] : Error: attribute "appendChar" has a bad value: the value does not match the regular expression ".". at line 16 , column 77._)
One more point to remove it :)

**Comment by youribonnaffe** [comment]
Hitting the delete key with the focus in a text field (for instance the command to run) deletes the task

**Comment by youribonnaffe** [comment]
I think I found the issue (see d994c7d).
The keyboard handling was just there inside the JobClasspath function...

**Comment by lpellegr** [comment]
:100:

**Pull request merged**
