### PR TITLE
Upgrade underscore to the last version

### PR DESCRIPTION
**Pull request by medou-boushab**

### CODE REVIEW

**Comment by medou-boushab** [comment]
retest please

**Comment by fviale** [comment]
Retest this please

**Comment by medou-boushab** [comment]
Retest this please

**Comment by fviale** [comment]
Retest this please

**Comment by medou-boushab** [comment]
Retest this please

**Comment by fviale** [comment]
Retest this please

**Comment by medou-boushab** [comment]
Retest this please

**Comment by fviale** [comment]
Retest this please

**Review by fviale — APPROVED** [review]

**Comment by medou-boushab** [comment]
Retest this please

**Comment by medou-boushab** [comment]
Retest this please

**Pull request merged**
