### PR TITLE
Merge native Linux and Windows workflow examples 

### PR DESCRIPTION
**Pull request by lpellegr**
This patch closes ow2-proactive/scheduling#2288.

### CODE REVIEW

**Comment by lpellegr** [comment]
@ow2-proactive/developers Could two people please review the changes?

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
@ow2-proactive/developers Could two people please review the changes?

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by marcocast** [comment]
:+1:

**Comment by paraita** [comment]
:+1:

**Pull request merged**
