### PR TITLE
Fix broken tests

### LINKED ISSUE #207: Broken UI tests after Firefox update
When Firefox updates itself, the selenium standalone server cannot communicate to the newer Firefox binary until it is also updated. This selenium standalone server jar is provided from the selenium website, and was built after every Firefox release. The same jar is now generated and distributed through npm so it can assure a more up to date version (instead of embedding it in the repository).
We should remove the binary and add the selenium standalone library as a npm dependency.
The bash script run by jenkins should handle the spawning of the selenium server (as it can fail when handled by nightwatch).

### PR DESCRIPTION
**Pull request by paraita**
Fixes #207 
The associated jenkins job has to be updated (spawn the selenium server).

### CODE REVIEW

**Comment by paraita** [comment]
retest this please.

**Comment by paraita** [comment]
retest this please.

**Comment by paraita** [comment]
retest this please.

**Comment by paraita** [comment]
retest this please.

**Comment by paraita** [comment]
retest this please.

**Comment by paraita** [comment]
retest this please.

**Comment by paraita** [comment]
retest this please.

**Comment by paraita** [comment]
@ow2-proactive/developers can 2 people review please ?

**Comment by tobwiens** [comment]
:+1: Cool that you added the build status to the readme.

**Comment by paraita** [comment]
Tests are passing on Linux.
I will force the merge, investigation are ongoing for the failing tests on Mac.

**Pull request merged**
