### PR TITLE
fixes #266: remove Cron Task in the model of Script

### LINKED ISSUE #266: Invalid "Cron Task" language option
It is possible to select _Cron Task_ as a language for a Task script (cf. screenshot). It makes no sense at all. 

The problem is probably related to the change which moved the _Cron task_ template from _Templates_ to _Task_ menu. It was reproductible on try platform with version 7.10.

capture d ecran de 2016-06-10 08-19-14

### PR DESCRIPTION
**Pull request by sophiesongge**
I just removed "Cron Task" in the model of Script

### CODE REVIEW

**Comment by sophiesongge** [comment]
retest please

**Comment by tobwiens** [comment]
:+1:

**Comment by marcocast** [comment]
👍

**Comment by sophiesongge** [comment]
Thank you both

**Pull request merged**
