### PR TITLE
Fix-vulnerabilities:: Avoid executing HTML code in the job name field

### PR DESCRIPTION
**Pull request by medou-boushab**

### CODE REVIEW

**Review by fviale — APPROVED** [review]
good idea

**Comment by fviale** [comment]
Retest this please

**Comment by fviale** [comment]
Retest this please

**Review by mbenguig — APPROVED** [review]

**Comment by medou-boushab** [comment]
Retest this please

**Comment by medou-boushab** [comment]
Retest this please

**Pull request merged**
